regular update

diff --git a/snakemake/snakefile b/snakemake/snakefile
--- a/snakemake/snakefile
+++ b/snakemake/snakefile
@@ -13,10 +13,10 @@ metadata_csv_list = [
     # "MC_muon_horizontal_metadata.csv",
     # "MC_muon_up_metadata.csv",
     # "MC_neutrino_volMuFilter_20fb-1_metadata.csv",
-     "MC_neutrino_volTarget_100fb-1_metadata.csv",
+    # "MC_neutrino_volTarget_100fb-1_metadata.csv",
     # "MC_neutron_FTFP_BERT_metadata.csv",
     # "MC_neutron_QGSP_BERT_HP_PEN_metadata.csv",
-    # "real_data_2022_metadata.csv",
+     "real_data_2022_metadata.csv",
     # "real_data_2023_metadata.csv",
     #  "real_data_2024_metadata.csv",
 ]
@@ -32,6 +32,7 @@ wildcard_constraints:
     model_output='.*model.*.root',
     eval_output = '.*eval.*.root',
     model_3d_output = '.*model.*.pkl.gz',
+    matrix_output=".*matrix.*.csv",
     #data_type="MC.*|real.*"
 
 
@@ -51,6 +52,28 @@ def load_metadata():
 
 METADATA = load_metadata()
 #print(METADATA)
+
+
+def get_metadata_from_output(output_path, target_name, output_type):
+    """
+    output_type: one of "model", "eval", or "matrix"
+    """
+    file_name = os.path.basename(output_path)
+    pattern = rf"{output_type}_(.+?)_output"
+    match = re.search(pattern, file_name)
+    if match:
+        m_name = match.group(1)
+        ref_name = f"{output_type}_{m_name}_output_path"
+        
+        if (output_type in {"eval", "matrix"}) and target_name == "model_output":
+            target_name = f"model_{m_name}_output_path"
+        elif output_type == "matrix" and target_name == "eval_output":
+            target_name = f"eval_{m_name}_output_path"
+
+        #print(".",(output_path, target_name, output_type))
+        return get_metadata_value(ref_name, output_path, target_name)
+    else:
+        print("Pattern not found.")
 
 def get_metadata_from_model_output(model_output, target_name):
     file_name = os.path.basename(model_output)
@@ -79,6 +102,7 @@ def get_metadata_from_eval_output(eval_output, target_name):
         print("Pattern not found.")
 
 def get_metadata_value(ref_name, ref_value, target_name):
+    #print((ref_name, ref_value, target_name))
     if METADATA is None:
        return ''
     return METADATA.loc[METADATA[ref_name] == ref_value, target_name].iloc[0]
@@ -128,19 +152,26 @@ def collect_model_path(target_name):
             paths = collect_target_paths(f"eval_{m}_output_path")
             target_paths.extend(paths)
         return target_paths
+    elif target_name == 'matrix_output':
+        target_paths = []
+        for m in model_name_list:
+            paths = collect_target_paths(f"matrix_{m}_output_path")
+            target_paths.extend(paths)
+        return target_paths
 
 rule finish:
     input:
         #expand("/afs/cern.ch/work/z/zhibin/snd-ml/snakemake/metadata/raw/{metadata_csv}", metadata_csv=metadata_csv_list),
-        expand("/afs/cern.ch/work/z/zhibin/snd-ml/snakemake/metadata/updated/{metadata_csv}", metadata_csv=metadata_csv_list),
+        #expand("/afs/cern.ch/work/z/zhibin/snd-ml/snakemake/metadata/updated/{metadata_csv}", metadata_csv=metadata_csv_list),
         #expand("{feature_path}", feature_path=collect_target_paths("feature_path")),
         #expand("{hit_path}", hit_path=collect_target_paths("hit_path")),
         #expand("{pt_hit_path}", pt_hit_path=collect_target_paths("pt_hit_path")),
         #expand("{pkl_hit_path}", pkl_hit_path=collect_target_paths("pkl_hit_path")),
         #expand("{model_3d_ckpt}", model_3d_ckpt=collect_model_path('ckpt')),
         #expand("{model_output}", model_output=collect_model_path('model_output')),
-        #expand("{eval_output}", eval_output=collect_model_path('eval_output')),
+        expand("{eval_output}", eval_output=collect_model_path('eval_output')),
         #expand("{model_3d_output}", model_3d_output=collect_model_path('model_output'))
+        #expand("{matrix_output}", matrix_output=collect_model_path('matrix_output')),
 
 
 rule generate_raw_metadata:
@@ -466,7 +497,7 @@ rule prediction_3d:
         #expand("{hit_path}", hit_path=collect_target_paths("hit_path")),
         #hit_path=lambda wildcards: get_metadata_value("pt_prefix", wildcards.pt_prefix, "hit_path"),
         #expand("{model_ckpt}", model_ckpt=collect_model_path('ckpt')),
-        pkl_hit_path=lambda wildcards: get_metadata_from_model_output(wildcards.model_3d_output, "pkl_hit_path"),
+        pkl_hit_path=lambda wildcards: get_metadata_from_output(wildcards.model_3d_output, "pkl_hit_path", "model"),
         script = '/afs/cern.ch/work/z/zhibin/snd-ml/training_3d/pred_3d.py',
     output:
         pred_output = "{model_3d_output}",
@@ -513,14 +544,14 @@ rule prediction:
         #expand("{hit_path}", hit_path=collect_target_paths("hit_path")),
         #hit_path=lambda wildcards: get_metadata_value("pt_prefix", wildcards.pt_prefix, "hit_path"),
         #expand("{model_ckpt}", model_ckpt=collect_model_path('ckpt')),
-        pt_hit_file=lambda wildcards: get_metadata_from_model_output(wildcards.model_output, "pt_hit_path"),
+        pt_hit_file=lambda wildcards: get_metadata_from_output(wildcards.model_output, "pt_hit_path", "model"),
         script = '/afs/cern.ch/work/z/zhibin/snd-ml/training/pred.py',
     output:
         pred_output = "{model_output}",
 
     threads:1
     resources:
-        runtime=2*60*60,
+        runtime=12*60*60,
         mem_mb=4000,
         disk_mb=4000,
         nvidia_gpu=0
@@ -555,14 +586,14 @@ rule prediction:
  
 rule evaluate:
     input:
-        model_output=lambda wildcards: get_metadata_from_eval_output(wildcards.eval_output, "model_output"),
-        feature_path=lambda wildcards: get_metadata_from_eval_output(wildcards.eval_output, "feature_path"),
+        model_output=lambda wildcards: get_metadata_from_output(wildcards.eval_output, "model_output", 'eval'),
+        feature_path=lambda wildcards: get_metadata_from_output(wildcards.eval_output, "feature_path", 'eval'),
         script = '/afs/cern.ch/user/z/zhibin/work/snd-ml/evaluation/evaluate.py'
     output:
         eval_output = '{eval_output}'
     threads:1
     resources:
-        runtime=60*60,
+        runtime=2*60*60,
         mem_mb=2000,
         disk_mb=2000,
         nvidia_gpu=0
@@ -597,20 +628,21 @@ rule evaluate:
 
 rule cal_matrix:
     input:
-        model_output=lambda wildcards: get_metadata_from_eval_output(wildcards.eval_output, "model_output"),
-        feature_path=lambda wildcards: get_metadata_from_eval_output(wildcards.eval_output, "feature_path"),
-        script = '/afs/cern.ch/user/z/zhibin/work/snd-ml/evaluation/evaluate.py'
+        model_output=lambda wildcards: get_metadata_from_output(wildcards.matrix_output, "model_output", "matrix"),
+        feature_path=lambda wildcards: get_metadata_from_output(wildcards.matrix_output, "feature_path", "matrix"),
+        eval_path=lambda wildcards: get_metadata_from_output(wildcards.matrix_output, "eval_output", "matrix"),
+        script = '/afs/cern.ch/user/z/zhibin/work/snd-ml/evaluation/cal_matrix.py'
     output:
-        eval_output = '{eval_output}'
+        matrix_output = '{matrix_output}'
     threads:1
     resources:
-        runtime=60*60,
+        runtime=29*60,
         mem_mb=2000,
         disk_mb=2000,
         nvidia_gpu=0
     shell:
         r"""
-        echo "running evaluation"
+        echo "running cal_matrix"
 
         # Avoid unbound variable error (only occurs when using Snakemake)
         set +u 
@@ -620,17 +652,22 @@ rule cal_matrix:
         export EOSSHIP=root://eosuser.cern.ch/
         # Create a unique temporary directory
         tmp_dir=$(mktemp -d)
-        filename=$(basename "{output.eval_output}")
+        filename=$(basename "{output.matrix_output}")
         tmp_output="${{tmp_dir}}/${{filename}}"
+
+        echo "tmp_dir: $tmp_dir"
+        echo "filename: $filename"
+        echo "tmp_output: $tmp_output"
 
         # Run evaluation script
         python {input.script} \
             -p {input.model_output} \
             -f {input.feature_path} \
+            -e {input.eval_path} \
             -o "${{tmp_output}}"
 
         # Copy result to final destination
-        xrdcp -f "${{tmp_output}}" "{output.eval_output}" || {{ echo "xrdcp failed"; exit 1; }}
+        xrdcp -f "${{tmp_output}}" "{output.matrix_output}" || {{ echo "xrdcp failed"; exit 1; }}
 
         # Cleanup
         rm -rf "${{tmp_dir}}"
