regular update

diff --git a/snakemake/snakefile b/snakemake/snakefile
--- a/snakemake/snakefile
+++ b/snakemake/snakefile
@@ -13,12 +13,12 @@ metadata_csv_list = [
     # "MC_muon_horizontal_metadata.csv",
     # "MC_muon_up_metadata.csv",
     # "MC_neutrino_volMuFilter_20fb-1_metadata.csv",
-    # "MC_neutrino_volTarget_100fb-1_metadata.csv",
-     "MC_neutron_FTFP_BERT_metadata.csv",
+     "MC_neutrino_volTarget_100fb-1_metadata.csv",
+    # "MC_neutron_FTFP_BERT_metadata.csv",
     # "MC_neutron_QGSP_BERT_HP_PEN_metadata.csv",
     # "real_data_2022_metadata.csv",
     # "real_data_2023_metadata.csv",
-    # "real_data_2024_metadata.csv",
+    #  "real_data_2024_metadata.csv",
 ]
 
 
@@ -28,8 +28,10 @@ wildcard_constraints:
     metadata_csv=".*metadata.*.csv",
     model_ckpt='.*ckpt.*',
     pt_hit_path = '.*pt_hit.*.pt.gz',
+    pkl_hit_path = '.*pkl_hit.*.pkl.gz',
     model_output='.*model.*.root',
     eval_output = '.*eval.*.root',
+    model_3d_output = '.*model.*.pkl.gz',
     #data_type="MC.*|real.*"
 
 
@@ -84,6 +86,12 @@ def get_metadata_value(ref_name, ref_value, target_name):
 def collect_target_paths(column_name):
     if METADATA is None:
        return ''
+
+    if '3d' in column_name:
+        # Filter out rows where 'split_3d_1' is 'train' or 'valid'
+        filtered = METADATA[~METADATA['split_3d_1'].isin(['train', 'valid'])]
+        return filtered[column_name].tolist()
+    
     return METADATA[column_name].tolist()
 
 def collect_model_path(target_name):
@@ -112,6 +120,7 @@ def collect_model_path(target_name):
         for m in model_name_list:
             paths = collect_target_paths(f"model_{m}_output_path")
             target_paths.extend(paths)
+        print(target_paths)
         return target_paths
     elif target_name == 'eval_output':
         target_paths = []
@@ -123,13 +132,15 @@ def collect_model_path(target_name):
 rule finish:
     input:
         #expand("/afs/cern.ch/work/z/zhibin/snd-ml/snakemake/metadata/raw/{metadata_csv}", metadata_csv=metadata_csv_list),
-        #expand("/afs/cern.ch/work/z/zhibin/snd-ml/snakemake/metadata/updated/{metadata_csv}", metadata_csv=metadata_csv_list),
+        expand("/afs/cern.ch/work/z/zhibin/snd-ml/snakemake/metadata/updated/{metadata_csv}", metadata_csv=metadata_csv_list),
         #expand("{feature_path}", feature_path=collect_target_paths("feature_path")),
         #expand("{hit_path}", hit_path=collect_target_paths("hit_path")),
         #expand("{pt_hit_path}", pt_hit_path=collect_target_paths("pt_hit_path")),
-        #expand("{model_ckpt}", model_ckpt=collect_model_path('ckpt')),
-        expand("{model_output}", model_output=collect_model_path('model_output')),
-        #expand("{eval_output}", eval_output=collect_model_path('eval_output'))
+        #expand("{pkl_hit_path}", pkl_hit_path=collect_target_paths("pkl_hit_path")),
+        #expand("{model_3d_ckpt}", model_3d_ckpt=collect_model_path('ckpt')),
+        #expand("{model_output}", model_output=collect_model_path('model_output')),
+        #expand("{eval_output}", eval_output=collect_model_path('eval_output')),
+        #expand("{model_3d_output}", model_3d_output=collect_model_path('model_output'))
 
 
 rule generate_raw_metadata:
@@ -279,6 +290,65 @@ rule process_features:
         """
 
 
+rule process_pkl_hit:
+    input:
+        script = "/afs/cern.ch/user/z/zhibin/work/snd-ml/convertData/digi_2_3Dhits.py",
+        #expand("/afs/cern.ch/work/z/zhibin/snd-ml/snakemake/metadata/updated/{metadata_csv}", metadata_csv=metadata_csv_list),
+        digi=lambda wildcards: get_metadata_value("pkl_hit_path", wildcards.pkl_hit_path, "digi_path"),
+        geo=lambda wildcards: get_metadata_value("pkl_hit_path", wildcards.pkl_hit_path, "geo_path"),
+        
+        #expand("{feature_path}", feature_path=collect_target_paths("feature_path")),
+        #expand("{hit_path}", hit_path=collect_target_paths("hit_path")),
+
+    params:
+        data_type=lambda wildcards: get_metadata_value("pkl_hit_path", wildcards.pkl_hit_path, "data_type"),
+        #env_file = "/afs/cern.ch/user/z/zhibin/work/snd-ml/snakemake/envs/env_sndsw.sh"
+        #pt_prefix = "{pt_prefix}"
+    output:
+        pkl_hit_path="{pkl_hit_path}"
+    threads:1
+    resources:
+        runtime=60*60,
+        mem_mb=2000,
+        disk_mb=2000,
+        nvidia_gpu=0
+    shell:
+        r"""
+        # Avoid sndsw and conda python conflict 
+        export PATH=$(echo $PATH | tr ':' '\n' | grep -v 'miniconda3' | tr '\n' ':' | sed 's/:$//')
+        
+        # Avoid unbound variable error (only occurs when using Snakemake)
+        set +u 
+        
+        echo "Setting up SNDSW"
+        export SNDLHC_mymaster=/afs/cern.ch/work/z/zhibin/public/SndBuild
+        export ALIBUILD_WORK_DIR=$SNDLHC_mymaster/sw
+        source /cvmfs/sndlhc.cern.ch/SNDLHC-2025/Jan30/setUp.sh
+        eval $(alienv load sndsw/latest-master-release --no-refresh)
+
+        export EOSSHIP=root://eosuser.cern.ch/
+
+        # Create a unique temporary directory
+        tmp_dir=$(mktemp -d)
+        filename=$(basename "{output.pkl_hit_path}")
+        tmp_output="${{tmp_dir}}/${{filename}}"
+
+        echo "Running process 3d hit script"
+        /cvmfs/sndlhc.cern.ch/SNDLHC-2024/June25/bin/python \
+            {input.script} \
+            -d {input.digi} \
+            -g {input.geo} \
+            -o "${{tmp_output}}" \
+            -t {params.data_type}
+
+        echo "Copying result to final location"
+        xrdcp -f "${{tmp_output}}" "{output.pkl_hit_path}" || {{ echo "xrdcp failed"; exit 1; }}
+
+        echo "Cleaning up"
+        rm -rf "${{tmp_dir}}"
+        """
+
+
 rule process_pt_hit:
     input:
         script = "/afs/cern.ch/user/z/zhibin/work/snd-ml/convertData/root_2_pt.py",
@@ -352,18 +422,54 @@ rule train:
         echo "train"
         """
 
+rule train_3d:
+    input:
+        #expand("/afs/cern.ch/work/z/zhibin/snd-ml/snakemake/metadata/updated/{metadata_csv}", metadata_csv=metadata_csv_list),
+        #expand("{feature_path}", feature_path=collect_target_paths("feature_path")),
+        #expand("{hit_path}", hit_path=collect_target_paths("hit_path"))
+        script = '/afs/cern.ch/work/z/zhibin/snd-ml/training_3d/train_3D.py',
+        model_config = '/afs/cern.ch/work/z/zhibin/snd-ml/training_3d/configs/baseline_3D.yml',
+        #config = 
+        #expand("{pt_hit_path}", pt_hit_path=collect_target_paths("pt_hit_path")),
+    #output:
+    #    trained_model = "{model_ckpt}"
+    
+    threads:2
+    resources:
+        runtime=8*60*60,
+        mem_mb=8000,
+        disk_mb=8000,
+        nvidia_gpu=1
+    shell:
+        r"""
+        echo "training 3d hit model"
+        #avoid unbound variable error (only occur when using snakemake)
+        set +u 
+        source /afs/cern.ch/work/z/zhibin/snd-ml/snakemake/envs/env_snd_pytorch.sh
+        export EOSSHIP=root://eosuser.cern.ch/
 
-rule prediction:
+        #tmp_dir_dataloader=$(mktemp -d)
+        export CUDA_VISIBLE_DEVICES=0
+        #nvidia-smi
+
+        
+        python {input.script} -c {input.model_config} 
+        """
+
+
+
+
+rule prediction_3d:
     input:
         #expand("/afs/cern.ch/work/z/zhibin/snd-ml/snakemake/metadata/updated/{metadata_csv}", metadata_csv=metadata_csv_list),
         #expand("{feature_path}", feature_path=collect_target_paths("feature_path")),
         #expand("{hit_path}", hit_path=collect_target_paths("hit_path")),
         #hit_path=lambda wildcards: get_metadata_value("pt_prefix", wildcards.pt_prefix, "hit_path"),
         #expand("{model_ckpt}", model_ckpt=collect_model_path('ckpt')),
-        pt_hit_file=lambda wildcards: get_metadata_from_model_output(wildcards.model_output, "pt_hit_path"),
-        script = '/afs/cern.ch/work/z/zhibin/snd-ml/training/pred.py',
+        pkl_hit_path=lambda wildcards: get_metadata_from_model_output(wildcards.model_3d_output, "pkl_hit_path"),
+        script = '/afs/cern.ch/work/z/zhibin/snd-ml/training_3d/pred_3d.py',
     output:
-        pred_output = "{model_output}",
+        pred_output = "{model_3d_output}",
 
     threads:1
     resources:
@@ -383,13 +489,15 @@ rule prediction:
         export EOSSHIP=root://eosuser.cern.ch/
         # Create a unique temporary directory
         tmp_dir=$(mktemp -d)
+        tmp_dir_dataloader=$(mktemp -d)
         filename=$(basename "{output.pred_output}")
         tmp_output="${{tmp_dir}}/${{filename}}"
 
         # Run prediction script
         python {input.script} \
-            -i {input.pt_hit_file} \
-            -o "${{tmp_output}}"
+            -i {input.pkl_hit_path} \
+            -o "${{tmp_output}}" \
+            -t "${{tmp_dir_dataloader}}"
 
         # Copy result to final destination
         xrdcp -f "${{tmp_output}}" "{output.pred_output}" || {{ echo "xrdcp failed"; exit 1; }}
@@ -398,6 +506,53 @@ rule prediction:
         rm -rf "${{tmp_dir}}"
         """
 
+rule prediction:
+    input:
+        #expand("/afs/cern.ch/work/z/zhibin/snd-ml/snakemake/metadata/updated/{metadata_csv}", metadata_csv=metadata_csv_list),
+        #expand("{feature_path}", feature_path=collect_target_paths("feature_path")),
+        #expand("{hit_path}", hit_path=collect_target_paths("hit_path")),
+        #hit_path=lambda wildcards: get_metadata_value("pt_prefix", wildcards.pt_prefix, "hit_path"),
+        #expand("{model_ckpt}", model_ckpt=collect_model_path('ckpt')),
+        pt_hit_file=lambda wildcards: get_metadata_from_model_output(wildcards.model_output, "pt_hit_path"),
+        script = '/afs/cern.ch/work/z/zhibin/snd-ml/training/pred.py',
+    output:
+        pred_output = "{model_output}",
+
+    threads:1
+    resources:
+        runtime=2*60*60,
+        mem_mb=4000,
+        disk_mb=4000,
+        nvidia_gpu=0
+    shell:
+        r"""
+        echo "running prediction"
+
+        # Avoid unbound variable error (only occurs when using Snakemake)
+        set +u 
+
+        # Set up environment
+        source /cvmfs/sft.cern.ch/lcg/views/setupViews.sh LCG_107_cuda x86_64-el9-gcc11-opt
+        export EOSSHIP=root://eosuser.cern.ch/
+        # Create a unique temporary directory
+        tmp_dir=$(mktemp -d)
+        tmp_dir_dataloader=$(mktemp -d)
+        filename=$(basename "{output.pred_output}")
+        tmp_output="${{tmp_dir}}/${{filename}}"
+
+        # Run prediction script
+        python {input.script} \
+            -i {input.pt_hit_file} \
+            -o "${{tmp_output}}" \
+            -t "${{tmp_dir_dataloader}}"
+
+        # Copy result to final destination
+        xrdcp -f "${{tmp_output}}" "{output.pred_output}" || {{ echo "xrdcp failed"; exit 1; }}
+
+        # Cleanup
+        rm -rf "${{tmp_dir}}"
+        """
+ 
 rule evaluate:
     input:
         model_output=lambda wildcards: get_metadata_from_eval_output(wildcards.eval_output, "model_output"),
@@ -407,7 +562,49 @@ rule evaluate:
         eval_output = '{eval_output}'
     threads:1
     resources:
-        runtime=14*60,
+        runtime=60*60,
+        mem_mb=2000,
+        disk_mb=2000,
+        nvidia_gpu=0
+    shell:
+        r"""
+        echo "running evaluation"
+
+        # Avoid unbound variable error (only occurs when using Snakemake)
+        set +u 
+
+        # Set up environment
+        source /cvmfs/sft.cern.ch/lcg/views/setupViews.sh LCG_107 x86_64-el9-gcc11-opt
+        export EOSSHIP=root://eosuser.cern.ch/
+        # Create a unique temporary directory
+        tmp_dir=$(mktemp -d)
+        filename=$(basename "{output.eval_output}")
+        tmp_output="${{tmp_dir}}/${{filename}}"
+
+        # Run evaluation script
+        python {input.script} \
+            -p {input.model_output} \
+            -f {input.feature_path} \
+            -o "${{tmp_output}}"
+
+        # Copy result to final destination
+        xrdcp -f "${{tmp_output}}" "{output.eval_output}" || {{ echo "xrdcp failed"; exit 1; }}
+
+        # Cleanup
+        rm -rf "${{tmp_dir}}"
+        """
+
+
+rule cal_matrix:
+    input:
+        model_output=lambda wildcards: get_metadata_from_eval_output(wildcards.eval_output, "model_output"),
+        feature_path=lambda wildcards: get_metadata_from_eval_output(wildcards.eval_output, "feature_path"),
+        script = '/afs/cern.ch/user/z/zhibin/work/snd-ml/evaluation/evaluate.py'
+    output:
+        eval_output = '{eval_output}'
+    threads:1
+    resources:
+        runtime=60*60,
         mem_mb=2000,
         disk_mb=2000,
         nvidia_gpu=0
